name: Deploy Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Setuo venv
      run: python -m venv env

    - name: Activate virtual env and Install dependencies
      run: |
        source env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write Firebase service account key to file
      run: echo "${{ secrets.GCP_SA_FIRESTORE_KEY }}" > ${HOME}/gcloud-service-account.json

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_GIT_SA_KEY }}'

    - name: Deploy to Cloud Function
      run: |
        gcloud config set run/region europe-west2
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud functions deploy rc-count-visits-cf \
          --runtime python38 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point count_page_visits \
          --region europe-west2